language: node_js
node_js:
  - "6"

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "VictorBu"
  - git config user.email "victorbu.xx@gmail.com"
  - echo "victor.karonda.com" > CNAME
  - git add .
  - git commit -m "add/edit"
  - git push --force --quiet "https://${github_token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
    
cache:
  directories:
    - node_modules
    
env:
 global:
   - GH_REF: github.com/VictorBu/victorbu.github.io.git
